name: Feature Branch Quality
on:
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node version 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: |
          npm ci
          npm run lint
          npm test
